- name: install nginx
  hosts: web
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: start nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: true
    